### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by abspython**
Initial Code for vaasu. And need to do the following in the future,

- [ ]  Add SQLite3 DB to store username & passwords.

- [ ] Fix the existing code and create function for _getID()_, _getPass()_ and _refresh()_.

- [ ] Code cleaning and Documentation.

Future Features to add,

- [ ] Add function for applying for duty leave.

### CODE REVIEW

**Comment by subins2000** [comment]
@abspython there's a lot of unwanted code in this. Remove em ?

**Comment by abspython** [comment]
This is just an initial commit. Those code may be helpful for future reference. Code cleaning is in the last stage of development.

**Comment by subins2000** [comment]
@abspython those location functions are absolutely not necessary. Perhaps remove those absolutely unwanted funcs ?

**Comment by abspython** [comment]
It is basically the example code from python-telegram-bot git repo. We could remove it in next commit.

**Pull request merged**
